# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image
FROM node:20-alpine AS build

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Build the TypeScript files
RUN npm run build

# Start a new stage for the production image
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Copy only the build output and package files from the build stage
COPY --from=build /app/build /app/build
COPY --from=build /app/package.json /app/package.json
COPY --from=build /app/package-lock.json /app/package-lock.json

# Install production dependencies only
RUN npm ci --omit=dev

# Define environment variables
ENV TAVILY_API_KEY=your-api-key-here

# Set the entrypoint to the MCP server
ENTRYPOINT ["node", "build/index.js"]