// Generated by Wrangler by running `wrangler types`

export interface Env {
	ENVIRONMENT: "production";
	TAVILY_API_KEY: string;
}

export interface ExecutionContext {
	waitUntil(promise: Promise<any>): void;
	passThroughOnException(): void;
}
