// @ts-nocheck
/**
 * AuditLoggerService — SOC 2–compliant structured audit logger.
 *
 * Emits newline-delimited JSON (NDJSON) audit events to stdout so that
 * Grafana Alloy / Loki / any log aggregator can ingest and index them.
 *
 * Every audit event carries:
 *   level        — always "audit" (allows log-router filtering)
 *   timestamp    — ISO 8601 UTC
 *   request_id   — UUID propagated from the HTTP request (X-Request-Id header
 *                  or auto-generated by AuditLogInterceptor)
 *   actor        — user / service identity performing the action
 *   action       — dot-namespaced verb  e.g. "payroll.run.approve"
 *   resource_id  — primary key of the affected entity
 *   result       — "success" | "failure"
 *   ...extras    — domain-specific fields (all PII already masked by caller)
 *
 * SOC 2 requirements satisfied:
 *   CC6.1  — Access control events logged with actor + resource
 *   CC7.2  — Security events (auth failures) logged with result=failure
 *   CC9.2  — Financial transaction events logged with amount + payment_count
 *   A1.2   — All log lines include timestamp + request_id for traceability
 *
 * Usage:
 *   constructor(private readonly audit: AuditLoggerService) {}
 *
 *   this.audit.log({
 *     requestId:  ctx.requestId,
 *     actor:      dto.createdBy,
 *     action:     'payroll.run.create',
 *     resourceId: run.id,
 *     result:     'success',
 *     extras: {
 *       payment_count: run.payments.length,
 *       amount_usd:    run.totalAmount,
 *     },
 *   });
 *
 * Required npm packages:
 *   (none — uses Node.js process.stdout directly for zero-dependency NDJSON)
 */

import { Injectable } from '@nestjs/common';

// ─── Types ────────────────────────────────────────────────────────────────────

export type AuditResult = 'success' | 'failure';

export interface AuditEvent {
  /** Correlation ID from the inbound HTTP request (X-Request-Id or generated). */
  requestId: string;
  /** Identity of the actor performing the action (user ID, service account, etc.). */
  actor: string;
  /**
   * Dot-namespaced action verb.
   * Convention: <domain>.<entity>.<verb>
   * Examples:
   *   payroll.run.create
   *   payroll.run.approve
   *   payroll.run.submit
   *   payroll.run.refresh_status
   *   jpm.payment.create
   *   jpm.callback.verify
   */
  action: string;
  /** Primary key of the affected entity (run UUID, payment ID, etc.). */
  resourceId: string;
  /** Outcome of the operation. */
  result: AuditResult;
  /**
   * Optional domain-specific fields.
   * MUST NOT contain raw PII — mask all account numbers, routing numbers,
   * and names before passing them here (use pii.util.ts helpers).
   */
  extras?: Record<string, unknown>;
}

// ─── Service ──────────────────────────────────────────────────────────────────

@Injectable()
export class AuditLoggerService {
  /**
   * Emit a structured audit event to stdout as NDJSON.
   *
   * The event is synchronously serialised and written so that it is never
   * lost even if the process exits immediately after (e.g. Lambda cold-start).
   *
   * @param event - The audit event to emit (all PII must be pre-masked).
   */
  log(event: AuditEvent): void {
    const record = {
      level:       'audit',
      timestamp:   new Date().toISOString(),
      request_id:  event.requestId,
      actor:       event.actor,
      action:      event.action,
      resource_id: event.resourceId,
      result:      event.result,
      ...(event.extras ?? {}),
    };

    // Write synchronously to stdout — avoids buffering issues in containers.
    process.stdout.write(JSON.stringify(record) + '\n');
  }

  /**
   * Convenience wrapper — emit a failure audit event with an error code.
   *
   * @param event     - Base audit event (result is forced to 'failure').
   * @param errorCode - Machine-readable error code (e.g. 'PAYROLL_RUN_NOT_FOUND').
   * @param message   - Human-readable error summary (no stack traces).
   */
  logFailure(
    event: Omit<AuditEvent, 'result'>,
    errorCode: string,
    message: string,
  ): void {
    this.log({
      ...event,
      result: 'failure',
      extras: {
        ...(event.extras ?? {}),
        error_code: errorCode,
        error_message: message,
      },
    });
  }
}
